.global gKaoGrookey
gKaoGrookey:
kao_siro sPortraitsGrookey
sGrookeyNormalPal:
.incbin "data/kao/customportraits/grookey/grookey_pained.pal"
sGrookeyNormalGfx:
.incbin "data/kao/customportraits/grookey/grookey_pained.at4px"
sGrookeyHappyPal:
.incbin "data/kao/customportraits/grookey/grookey_happy.pal"
sGrookeyHappyGfx:
.incbin "data/kao/customportraits/grookey/grookey_happy.at4px"
sGrookeyPainedPal:
.incbin "baserom.gba", 0x168A8A0, 0x40
sGrookeyPainedGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168A8E5, 0x263
sGrookeyAngryPal:
.incbin "baserom.gba", 0x168AB48, 0x40
sGrookeyAngryGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168AB8D, 0x2AB
sGrookeyWorriedPal:
.incbin "baserom.gba", 0x168AE38, 0x40
sGrookeyWorriedGfx:
.incbin "baserom.gba", 0x168AE78, 0x260
sGrookeySadPal:
.incbin "baserom.gba", 0x168B0D8, 0x40
sGrookeySadGfx:
.incbin "baserom.gba", 0x168B118, 0x254
sGrookeyCryingPal:
.incbin "baserom.gba", 0x168B36C, 0x40
sGrookeyCryingGfx:
.incbin "baserom.gba", 0x168B3AC, 0x2A4
sGrookeyShoutingPal:
.incbin "baserom.gba", 0x168B650, 0x40
sGrookeyShoutingGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168B695, 0x293
sGrookeyTearyEyePal:
.incbin "baserom.gba", 0x168B928, 0x40
sGrookeyTearyEyeGfx:
.incbin "baserom.gba", 0x168B968, 0x274
sGrookeyDeterminedPal:
.incbin "baserom.gba", 0x168BBDC, 0x40
sGrookeyDeterminedGfx:
.incbin "baserom.gba", 0x168BC1C, 0x244
sGrookeyJoyousPal:
.incbin "baserom.gba", 0x168BE60, 0x40
sGrookeyJoyousGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x168BEA5, 0x2A3
sGrookeyInspiredPal:
.incbin "baserom.gba", 0x168C148, 0x40
sGrookeyInspiredGfx:
.incbin "baserom.gba", 0x168C188, 0x26C
sGrookeySurprisedPal:
.incbin "baserom.gba", 0x168C3F4, 0x40
sGrookeySurprisedGfx:
.incbin "baserom.gba", 0x168C434, 0x29C
sPortraitsGrookey:
kao_portrait sGrookeyNormalPal, sGrookeyNormalGfx
kao_portrait sGrookeyHappyPal, sGrookeyHappyGfx
kao_portrait sGrookeyPainedPal, sGrookeyPainedGfx
kao_portrait sGrookeyAngryPal, sGrookeyAngryGfx
kao_portrait sGrookeyWorriedPal, sGrookeyWorriedGfx
kao_portrait sGrookeySadPal, sGrookeySadGfx
kao_portrait sGrookeyCryingPal, sGrookeyCryingGfx
kao_portrait sGrookeyShoutingPal, sGrookeyShoutingGfx
kao_portrait sGrookeyTearyEyePal, sGrookeyTearyEyeGfx
kao_portrait sGrookeyDeterminedPal, sGrookeyDeterminedGfx
kao_portrait sGrookeyJoyousPal, sGrookeyJoyousGfx
kao_portrait sGrookeyInspiredPal, sGrookeyInspiredGfx
kao_portrait sGrookeySurprisedPal, sGrookeySurprisedGfx
